### ISSUE TITLE
same package name in multiple fidl files

### ISSUE THREAD

**Issue by jb090979** [zayfod/pyfranca#5]
I check the latest Version 0.2.1 and run into some trouble with the processor. The process checks that the package.name  is not defined in multiple files. But as I understand Franca IDL this is a valid syntax. The package.name is the scope of the interfaces and typecollections and I can split a scope over multiple files.

Attached please find 2 fidl files. Your validator told me a circular dependency. But the official CommonAPI Generator accept these fidls files.

fidl_validator.py  -I packages Hello.fidl  definitions.fidl 
ERROR: Circular dependency for package 'myPackage'.

As I understand franca_processor.py the problem is that you use the package.name as the key name of an package. If you take a look into my franca_validator.py I use the fidl file name as the key name. I am not sure that the fild file in the import instruction is just the file name or is it a path. I assume it is a path. The franca user guide does not sepcify the import instruction completely.
import myPackage.MyTypes.* from "definitions.fidl"

franca_processor.py Line 339
self.packages[package.name] = package

franca_validator.py Line 34
abs_path = os.path.abspath(fspec)
self.packages[abs_path] = fpackage

best regards
jens

[fidl.tar.gz](https://github.com/zayfod/pyfranca/files/852347/fidl.tar.gz)

**Comment by zayfod** [comment]
You are correct - using the same package name in multiple files is valid Franca syntax.

The decision, not to support this in the first release of the processor module was intentional so that the implementation can be simplified. This is currently stated in the README as a limitation. Supporting packages, spread across multiple files is not very hard but requires validation that there are no duplicate member definitions in multiple files.

I would like to still use the package name as a key in the packages dictionary. Instead, packages, declared in multiple files can be merged together by the processor.

I can give this a try in the next few days if you help with validating the correct behavior afterwards.

**Comment by jb090979** [comment]
Sorry I miss reading the updated limitations.


I realy like the idea of merging packages, declared in multiple files together. This is better then my approach in franca_validator.py. I can support you in validating the behavior.

**Comment by zayfod** [comment]
This turned out to be much easier than I expected. The dev branch now interprets correctly the example that you provided.

Looking forward to your feedback.

**Comment by zayfod** [comment]
Released with v0.3.0 .
